INSERT INTO USER (ID, USER_ID , PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (1, 'MELON' ,'123','PAIK', 'MELON9751@NAVER.COM', CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID , PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (2, 'APPLE' ,'123','HONG', 'MELON975123@NAVER.COM', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID, COUNT_OF_ANSWER) VALUES (1, '123', CURRENT_TIMESTAMP(), 'pes6 질문입니다', 1, 0);
INSERT INTO QUESTION (ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID, COUNT_OF_ANSWER) VALUES (2, '234', CURRENT_TIMESTAMP(), 'NETWORK', 2, 0);